// <auto-generated />
using System;
using Contable.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contable.Infrastructure.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    [Migration("20251011133458_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Contable.Domain.Entities.Anticipo", b =>
                {
                    b.Property<int>("AnticipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnticipoId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PorcentajeAnticipo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AnticipoId");

                    b.ToTable("Anticipo", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Caja", b =>
                {
                    b.Property<int>("CajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CajaId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CajaId");

                    b.ToTable("Caja", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AnticipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InventarioId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroFactura")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int>("TerceroId")
                        .HasColumnType("int");

                    b.Property<int>("TipoFacturaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPagoId")
                        .HasColumnType("int");

                    b.Property<int>("Unidades")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("AnticipoId");

                    b.HasIndex("InventarioId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TerceroId");

                    b.HasIndex("TipoFacturaId");

                    b.HasIndex("TipoPagoId");

                    b.ToTable("Factura", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Inventario", b =>
                {
                    b.Property<int>("InventarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventarioId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrecioCompraInventario")
                        .HasColumnType("int");

                    b.Property<int>("PrecioVentaInventario")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesInventario")
                        .HasColumnType("int");

                    b.HasKey("InventarioId");

                    b.ToTable("Inventario", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Rol", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServicioId");

                    b.ToTable("Servicio", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Tercero", b =>
                {
                    b.Property<int>("TerceroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerceroId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoTercero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CiudadTercero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronicoTercero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionTercero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreTercero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDoc")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocialTercero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoTercero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTerceroId")
                        .HasColumnType("int");

                    b.HasKey("TerceroId");

                    b.HasIndex("TipoDocId");

                    b.HasIndex("TipoTerceroId");

                    b.ToTable("Tercero", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.TipoDoc", b =>
                {
                    b.Property<int>("TipoDocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoDocId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoDocId");

                    b.ToTable("TipoDoc", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.TipoFactura", b =>
                {
                    b.Property<int>("TipoFacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoFacturaId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoFacturaId");

                    b.ToTable("TipoFactura", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.TipoPago", b =>
                {
                    b.Property<int>("TipoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoPagoId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoPagoId");

                    b.ToTable("TipoPago", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.TipoTercero", b =>
                {
                    b.Property<int>("TipoTerceroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoTerceroId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoTerceroId");

                    b.ToTable("TipoTercero", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronicoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUserGoogle")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroDocumentoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoDocId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.HasIndex("TipoDocId");

                    b.ToTable("Usuario", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Factura", b =>
                {
                    b.HasOne("Contable.Domain.Entities.Anticipo", "Anticipo")
                        .WithMany("Facturas")
                        .HasForeignKey("AnticipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entities.Inventario", null)
                        .WithMany("Facturas")
                        .HasForeignKey("InventarioId");

                    b.HasOne("Contable.Domain.Entities.Producto", "Producto")
                        .WithMany("Facturas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Facturas")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entities.Tercero", "Tercero")
                        .WithMany("Facturas")
                        .HasForeignKey("TerceroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entities.TipoFactura", "TipoFactura")
                        .WithMany("Facturas")
                        .HasForeignKey("TipoFacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entities.TipoPago", "TipoDePago")
                        .WithMany("Facturas")
                        .HasForeignKey("TipoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anticipo");

                    b.Navigation("Producto");

                    b.Navigation("Servicio");

                    b.Navigation("Tercero");

                    b.Navigation("TipoDePago");

                    b.Navigation("TipoFactura");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Tercero", b =>
                {
                    b.HasOne("Contable.Domain.Entities.TipoDoc", "TipoDoc")
                        .WithMany("Terceros")
                        .HasForeignKey("TipoDocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entities.TipoTercero", "TipoTercero")
                        .WithMany("Terceros")
                        .HasForeignKey("TipoTerceroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDoc");

                    b.Navigation("TipoTercero");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Contable.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Contable.Domain.Entities.TipoDoc", "TipoDoc")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoDocId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Rol");

                    b.Navigation("TipoDoc");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Anticipo", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Inventario", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Contable.Domain.Entities.Tercero", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Contable.Domain.Entities.TipoDoc", b =>
                {
                    b.Navigation("Terceros");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Contable.Domain.Entities.TipoFactura", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Contable.Domain.Entities.TipoPago", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Contable.Domain.Entities.TipoTercero", b =>
                {
                    b.Navigation("Terceros");
                });
#pragma warning restore 612, 618
        }
    }
}
