// <auto-generated />
using System;
using Contable.Infrastructure.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contable.Infrastructure.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    partial class PersistenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Contable.Domain.Entidades.Anticipos", b =>
                {
                    b.Property<int>("AnticiposId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnticiposId"), 1L, 1);

                    b.Property<int?>("ClientesId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("PorcentajeAnticipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnticiposId");

                    b.HasIndex("ClientesId");

                    b.HasIndex("IdRol");

                    b.ToTable("Anticipos", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Clientes", b =>
                {
                    b.Property<int>("ClientesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientesId"), 1L, 1);

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronicoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("IdTipoIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroIdCliente")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientesId");

                    b.HasIndex("IdRol");

                    b.ToTable("Clientes", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Compras", b =>
                {
                    b.Property<int>("ComprasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComprasId"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPago")
                        .HasColumnType("int");

                    b.Property<int>("PrecioCompra")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesCompra")
                        .HasColumnType("int");

                    b.HasKey("ComprasId");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoPago");

                    b.ToTable("Compras", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Costos", b =>
                {
                    b.Property<int>("CostosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostosId"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCompraCostos")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPago")
                        .HasColumnType("int");

                    b.Property<int>("PrecioCostos")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesCostos")
                        .HasColumnType("int");

                    b.HasKey("CostosId");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoPago");

                    b.ToTable("Costos", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Gastos", b =>
                {
                    b.Property<int>("GastosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastosId"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCompraGastos")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPago")
                        .HasColumnType("int");

                    b.Property<int>("PrecioGastos")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesGastos")
                        .HasColumnType("int");

                    b.HasKey("GastosId");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoPago");

                    b.ToTable("Gastos", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Inventario", b =>
                {
                    b.Property<int>("InventarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventarioId"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("PrecioCompraInventario")
                        .HasColumnType("int");

                    b.Property<int>("PrecioVentaInventario")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesInventario")
                        .HasColumnType("int");

                    b.HasKey("InventarioId");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdRol");

                    b.ToTable("Inventario", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("RolId");

                    b.ToTable("Item", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Proveedores", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"), 1L, 1);

                    b.Property<string>("ApellidoProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronicoProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("IdTipoIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroIdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoDeIdentificacionTipoIdentificacionId")
                        .HasColumnType("int");

                    b.HasKey("ProveedorId");

                    b.HasIndex("TipoDeIdentificacionTipoIdentificacionId");

                    b.ToTable("Proveedores", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"), 1L, 1);

                    b.Property<string>("DescripcionRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Rol", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Tesoreria", b =>
                {
                    b.Property<int>("TesoreriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TesoreriaId"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoDisponible")
                        .HasColumnType("int");

                    b.Property<int>("ValorDisponible")
                        .HasColumnType("int");

                    b.HasKey("TesoreriaId");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoDisponible");

                    b.ToTable("Tesoreria", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.TipodeDisponible", b =>
                {
                    b.Property<int>("TipoDisponibleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoDisponibleId"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreTipoDisponible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.HasKey("TipoDisponibleId");

                    b.HasIndex("RolId");

                    b.ToTable("TipodeDisponible", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.TipoDeIdentificacion", b =>
                {
                    b.Property<int>("TipoIdentificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoIdentificacionId"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreTipoIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.HasKey("TipoIdentificacionId");

                    b.HasIndex("RolId");

                    b.ToTable("TipoDeIdentificacion", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.TipoDePago", b =>
                {
                    b.Property<int>("TipoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoPagoId"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreTipoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoPagoId");

                    b.ToTable("TipoDePago", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"), 1L, 1);

                    b.Property<string>("ApellidoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContrasenaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronicoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroIdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoIdentificacion");

                    b.ToTable("Usuario", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Ventas", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnticipo")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPago")
                        .HasColumnType("int");

                    b.Property<int>("PrecioVenta")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesVenta")
                        .HasColumnType("int");

                    b.HasKey("VentaId");

                    b.HasIndex("IdAnticipo");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoPago");

                    b.ToTable("Ventas", "dbo");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Anticipos", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClientesId");

                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany("Anticipos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Clientes", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany("Clientes")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Compras", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Proveedores", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany("Compras")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.TipoDePago", "TipoDePago")
                        .WithMany("Compras")
                        .HasForeignKey("IdTipoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Rol");

                    b.Navigation("TipoDePago");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Costos", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Proveedores", "Proveedor")
                        .WithMany("Costos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany("Costos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.TipoDePago", "TipoDePago")
                        .WithMany("Costos")
                        .HasForeignKey("IdTipoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Rol");

                    b.Navigation("TipoDePago");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Gastos", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Proveedores", "Proveedor")
                        .WithMany("Gastos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany("Gastos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.TipoDePago", "TipoDePago")
                        .WithMany("Gastos")
                        .HasForeignKey("IdTipoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Rol");

                    b.Navigation("TipoDePago");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Inventario", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Item", "Item")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Item", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Proveedores", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.TipoDeIdentificacion", null)
                        .WithMany("Proveedores")
                        .HasForeignKey("TipoDeIdentificacionTipoIdentificacionId");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Tesoreria", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.TipodeDisponible", "TipoDisponible")
                        .WithMany("Tesorerias")
                        .HasForeignKey("IdTipoDisponible")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("TipoDisponible");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.TipodeDisponible", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.TipoDeIdentificacion", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.TipoDeIdentificacion", "TipoIdentificacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Ventas", b =>
                {
                    b.HasOne("Contable.Domain.Entidades.Anticipos", "Anticipo")
                        .WithMany("Ventas")
                        .HasForeignKey("IdAnticipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.Clientes", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contable.Domain.Entidades.TipoDePago", "TipoPago")
                        .WithMany("Ventas")
                        .HasForeignKey("IdTipoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anticipo");

                    b.Navigation("Cliente");

                    b.Navigation("Rol");

                    b.Navigation("TipoPago");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Anticipos", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Clientes", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Item", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Proveedores", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Costos");

                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.Rol", b =>
                {
                    b.Navigation("Anticipos");

                    b.Navigation("Clientes");

                    b.Navigation("Compras");

                    b.Navigation("Costos");

                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.TipodeDisponible", b =>
                {
                    b.Navigation("Tesorerias");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.TipoDeIdentificacion", b =>
                {
                    b.Navigation("Proveedores");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Contable.Domain.Entidades.TipoDePago", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Costos");

                    b.Navigation("Gastos");

                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
